<?php

return array(

  'states' => array(
    'ad' => 'ad',
    'al' => 'al',
    'am' => 'am',
    'at' => 'at',
    'az' => 'az',
    'ba' => 'ba',
    'be' => 'be',
    'bg' => 'bg',
    'hr' => 'hr',
    'ch' => 'ch',
    'cy' => 'cy',
    'cz' => 'cz',
    'de' => 'de',
    'dk' => 'dk',
    'ee' => 'ee',
    'es' => 'es',
    'fi' => 'fi',
    'fr' => 'fr',
    'ge' => 'ge',
    'gr' => 'gr',
    'hu' => 'hu',
    'ie' => 'ie',
    'is' => 'is',
    'it' => 'it',
    'li' => 'li',
    'lt' => 'lt',
    'lu' => 'lu',
    'lv' => 'lv',
    'mc' => 'mc',
    'md' => 'md',
    'me' => 'me',
    'mk' => 'mk',
    'mt' => 'mt',
    'nl' => 'nl',
    'no' => 'no',
    'pl' => 'pl',
    'pt' => 'pt',
    'ro' => 'ro',
    'rs' => 'rs',
    'ru' => 'ru',
    'se' => 'se',
    'si' => 'si',
    'sk' => 'sk',
    'sm' => 'sm',
    'tr' => 'tr',
    'ua' => 'ua',
    'uk' => 'uk',
  ),

  'langs' => array(
    'az' => 'az',
    'bg' => 'bg',
    'bs' => 'bs',
    'ca' => 'ca',
    'cs' => 'cs',
    'da' => 'da',
    'de' => 'de',
    'el' => 'el',
    'en' => 'en',
    'es' => 'es',
    'et' => 'et',
    'fi' => 'fi',
    'fr' => 'fr',
    'ga' => 'ga',
    'hr' => 'hr',
    'hu' => 'hu',
    'hy' => 'hy',
    'is' => 'is',
    'it' => 'it',
    'ka' => 'ka',
    'lb' => 'lb',
    'lt' => 'lt',
    'lv' => 'lv',
    'mk' => 'mk',
    'mo' => 'mo',
    'mt' => 'mt',
    'nl' => 'nl',
    'no' => 'no',
    'pl' => 'pl',
    'pt' => 'pt',
    'ro' => 'ro',
    'ru' => 'ru',
    'sk' => 'sk',
    'sl' => 'sl',
    'sq' => 'sq',
    'sr' => 'sr',
    'sv' => 'sv',
    'tr' => 'tr',
    'uk' => 'uk',
  ),

);
